name: Fetch from working-data and process

on: 
  push:
  workflow_dispatch:
  repository_dispatch:

jobs:
  fetch_and_process:
    name: Fetch from working-data and process
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx5g
      TYPESENSE_SEARCH_KEY: ${{secrets.TYPESENSE_SEARCH_KEY}}
      TYPESENSE_API_KEY: ${{secrets.TYPESENSE_API_KEY}}
      TYPESENSE_HOST: ${{secrets.TYPESENSE_HOST}}
      TYPESENSE_PORT: ${{vars.TYPESENSE_PORT}}
      TYPESENSE_PROTOCOL: ${{vars.TYPESENSE_PROTOCOL}}
      GITHUB_USER_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    - name: prepare folders
      run: |
        mkdir -p data/editions
        rm -rf data/editions/*
    - name: fetch data
      run: |  
        ./shellscripts/fetch_tei_data.sh
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: fetched data from working-data & transkribus-export
    - name: trigger fetch-wf in bv-static
      run: |
        status=$(curl --request POST \
        --url 'https://api.github.com/repos/bundesverfassung-oesterreich/bv-static/dispatches' \
        --header "authorization: token $GITHUB_USER_TOKEN" \
        --data '{"event_type": "fetch worflow triggerd by push in data"}')
        if [ -n "$status" ]; then  exit 1; fi
        echo "workflow seems to be running"